import math

RES = WIDTH, HEIGHT = 1200,700
HALF_WIDTH = WIDTH//2
HALF_HEIGHT = HEIGHT//2
FPS = 60

#player
PLAYER_POS = 1.5, 5 #mini map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100

#mouse
MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

#ray cast
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS=WIDTH // 2
HALF_NUM_RAY= NUM_RAYS//2
DELTA_ANGLE = FOV/NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH/math.tan(HALF_FOV)
SCALE = WIDTH//NUM_RAYS

#resource
RSC_SIZE = 256
HALF_RSC_SIZE = RSC_SIZE//2 
FLOOR_COLOR = (30,30,30)